name: ws-ad-alert
run-name: ${{ github.actor }} is using actions
on: [push]
jobs:
  build-lambda-zip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: npm install, lambda-pack
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: |
          npm install
          npm run-script lambda-pack
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: lambda-zip
          path: lambda.zip
